remote_theme: "mmistakes/minimal-mistakes@4.26.2"
title: "SpaCCI"
description: "Spatially Aware Cell-Cell Interaction Anaylsis"
baseurl: "/SpaCCI" # You might need to set this based on your site structure
url: "https://litingku.github.io" # Your GitHub Pages URL
enable_copy_code_button: true
plugins:
  - jekyll-include-cache

# Add settings for social links if needed
social_links:
  - title: "GitHub"
    url: "https://github.com/LitingKu/SpaCCI"


#

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc_sticky: true
      toc: true
      sidebar:
        nav: "docs"
        
collections:
  docs:
    output: true
    permalink: /:collection/:path/


assets:
  stylesheets:
    - /assets/css/custom.scss

